//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace GestaoTributos.Data.wsLoteContabil {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="sapiens_Synccom_senior_g5_co_mct_ctb_gerarlotectbPortBinding", Namespace="http://services.senior.com.br")]
    public partial class g5seniorservices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GerarOperationCompleted;
        
        private System.Threading.SendOrPostCallback Gerar_2OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public g5seniorservices() {
            this.Url = global::GestaoTributos.Data.Properties.Settings.Default.GestaoTributos_Data_wsLoteContabil_g5_senior_services;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GerarCompletedEventHandler GerarCompleted;
        
        /// <remarks/>
        public event Gerar_2CompletedEventHandler Gerar_2Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://services.senior.com.br", ResponseNamespace="http://services.senior.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public gerarlotectbGerarOut Gerar(string user, string password, int encryption, gerarlotectbGerarIn parameters) {
            object[] results = this.Invoke("Gerar", new object[] {
                        user,
                        password,
                        encryption,
                        parameters});
            return ((gerarlotectbGerarOut)(results[0]));
        }
        
        /// <remarks/>
        public void GerarAsync(string user, string password, int encryption, gerarlotectbGerarIn parameters) {
            this.GerarAsync(user, password, encryption, parameters, null);
        }
        
        /// <remarks/>
        public void GerarAsync(string user, string password, int encryption, gerarlotectbGerarIn parameters, object userState) {
            if ((this.GerarOperationCompleted == null)) {
                this.GerarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGerarOperationCompleted);
            }
            this.InvokeAsync("Gerar", new object[] {
                        user,
                        password,
                        encryption,
                        parameters}, this.GerarOperationCompleted, userState);
        }
        
        private void OnGerarOperationCompleted(object arg) {
            if ((this.GerarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GerarCompleted(this, new GerarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://services.senior.com.br", ResponseNamespace="http://services.senior.com.br", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public gerarlotectbGerar2Out Gerar_2(string user, string password, int encryption, gerarlotectbGerar2In parameters) {
            object[] results = this.Invoke("Gerar_2", new object[] {
                        user,
                        password,
                        encryption,
                        parameters});
            return ((gerarlotectbGerar2Out)(results[0]));
        }
        
        /// <remarks/>
        public void Gerar_2Async(string user, string password, int encryption, gerarlotectbGerar2In parameters) {
            this.Gerar_2Async(user, password, encryption, parameters, null);
        }
        
        /// <remarks/>
        public void Gerar_2Async(string user, string password, int encryption, gerarlotectbGerar2In parameters, object userState) {
            if ((this.Gerar_2OperationCompleted == null)) {
                this.Gerar_2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGerar_2OperationCompleted);
            }
            this.InvokeAsync("Gerar_2", new object[] {
                        user,
                        password,
                        encryption,
                        parameters}, this.Gerar_2OperationCompleted, userState);
        }
        
        private void OnGerar_2OperationCompleted(object arg) {
            if ((this.Gerar_2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Gerar_2Completed(this, new Gerar_2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class gerarlotectbGerarIn {
        
        private System.Nullable<int> codEmpField;
        
        private bool codEmpFieldSpecified;
        
        private System.Nullable<int> codFilField;
        
        private bool codFilFieldSpecified;
        
        private string datLotField;
        
        private string desLotField;
        
        private string flowInstanceIDField;
        
        private string flowNameField;
        
        private string oriLotField;
        
        private System.Nullable<double> totLotField;
        
        private bool totLotFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<int> codEmp {
            get {
                return this.codEmpField;
            }
            set {
                this.codEmpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codEmpSpecified {
            get {
                return this.codEmpFieldSpecified;
            }
            set {
                this.codEmpFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<int> codFil {
            get {
                return this.codFilField;
            }
            set {
                this.codFilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codFilSpecified {
            get {
                return this.codFilFieldSpecified;
            }
            set {
                this.codFilFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string datLot {
            get {
                return this.datLotField;
            }
            set {
                this.datLotField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string desLot {
            get {
                return this.desLotField;
            }
            set {
                this.desLotField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string flowInstanceID {
            get {
                return this.flowInstanceIDField;
            }
            set {
                this.flowInstanceIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string flowName {
            get {
                return this.flowNameField;
            }
            set {
                this.flowNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string oriLot {
            get {
                return this.oriLotField;
            }
            set {
                this.oriLotField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<double> totLot {
            get {
                return this.totLotField;
            }
            set {
                this.totLotField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totLotSpecified {
            get {
                return this.totLotFieldSpecified;
            }
            set {
                this.totLotFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class gerarlotectbGerar2Out {
        
        private string erroExecucaoField;
        
        private System.Nullable<int> numLotField;
        
        private bool numLotFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string erroExecucao {
            get {
                return this.erroExecucaoField;
            }
            set {
                this.erroExecucaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<int> numLot {
            get {
                return this.numLotField;
            }
            set {
                this.numLotField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numLotSpecified {
            get {
                return this.numLotFieldSpecified;
            }
            set {
                this.numLotFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class gerarlotectbGerar2In {
        
        private System.Nullable<int> codEmpField;
        
        private bool codEmpFieldSpecified;
        
        private System.Nullable<int> codFilField;
        
        private bool codFilFieldSpecified;
        
        private string datLotField;
        
        private string desLotField;
        
        private string flowInstanceIDField;
        
        private string flowNameField;
        
        private string oriLotField;
        
        private string tipLotField;
        
        private System.Nullable<double> totLotField;
        
        private bool totLotFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<int> codEmp {
            get {
                return this.codEmpField;
            }
            set {
                this.codEmpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codEmpSpecified {
            get {
                return this.codEmpFieldSpecified;
            }
            set {
                this.codEmpFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<int> codFil {
            get {
                return this.codFilField;
            }
            set {
                this.codFilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codFilSpecified {
            get {
                return this.codFilFieldSpecified;
            }
            set {
                this.codFilFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string datLot {
            get {
                return this.datLotField;
            }
            set {
                this.datLotField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string desLot {
            get {
                return this.desLotField;
            }
            set {
                this.desLotField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string flowInstanceID {
            get {
                return this.flowInstanceIDField;
            }
            set {
                this.flowInstanceIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string flowName {
            get {
                return this.flowNameField;
            }
            set {
                this.flowNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string oriLot {
            get {
                return this.oriLotField;
            }
            set {
                this.oriLotField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string tipLot {
            get {
                return this.tipLotField;
            }
            set {
                this.tipLotField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<double> totLot {
            get {
                return this.totLotField;
            }
            set {
                this.totLotField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totLotSpecified {
            get {
                return this.totLotFieldSpecified;
            }
            set {
                this.totLotFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class gerarlotectbGerarOut {
        
        private string erroExecucaoField;
        
        private System.Nullable<int> numLotField;
        
        private bool numLotFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string erroExecucao {
            get {
                return this.erroExecucaoField;
            }
            set {
                this.erroExecucaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<int> numLot {
            get {
                return this.numLotField;
            }
            set {
                this.numLotField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numLotSpecified {
            get {
                return this.numLotFieldSpecified;
            }
            set {
                this.numLotFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GerarCompletedEventHandler(object sender, GerarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GerarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GerarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public gerarlotectbGerarOut Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((gerarlotectbGerarOut)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void Gerar_2CompletedEventHandler(object sender, Gerar_2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Gerar_2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Gerar_2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public gerarlotectbGerar2Out Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((gerarlotectbGerar2Out)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591